title: Shishir Sonekar - My corner of the internet
description: > # this means to ignore newlines until "baseurl:"
  A Software Engineer.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shishirsonekar.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: https://twitter.com/shishirViz #if your site has a twitter account, enter it here

# Author Settings
author: Shishir Sonekar # add your name
author-img: pp5.jpg # add your photo
about-author: Software Developer | AWS | MicroServices | Go | Kubernetes | Nodejs | React | Web Development. # add description
social-twitter: shishirViz # add your Twitter handle
social-github: shishir-sonekar # add your Github handle
social-linkedin: shishirsonekar # add your Linkedin handle
social-email: shishir.sonekar@gmail.com # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: Google Analytics # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
